services:
  cache:
    image: redis:6
    healthcheck:
      test: ["CMD-SHELL", "[ $$(redis-cli ping) = 'PONG' ]"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_interval: 5s
      start_period: 30s

  directus:
    image: directus/directus:11.5.1
    ports:
      - 80:8055
      - 443:8055
    volumes:
      - uploads:/directus/uploads
      - extensions:/directus/extensions
      - ./db-snapshot:/directus/db-snapshot
    command: ["sh", "-c", "npx directus bootstrap && npx directus schema apply -y ./db-snapshot && npx directus start"]
    depends_on:
      database:
        condition: service_healthy
      cache:
        condition: service_healthy
    env_file:
      - ./env

volumes:
  uploads:
  extensions: